// Customizer const
export const TOGGLE_COLLAPSED_NAV = 'TOGGLE_COLLAPSE_MENU'
export const WINDOW_WIDTH = 'WINDOW-WIDTH'
export const REQUEST_USER = 'REQUEST_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
